### ISSUE TITLE
关于工作室中使用KKS_StudioTextPlugin时遇到的Bug

### ISSUE THREAD

**Issue by Kamisato100** [jim60105/KK#13]
你好，我在使用KKS_StudioTextPlugin_1.2.0时在工作室中遇到了一个奇怪的问题，当我使用某一种字体较多时就会频繁出现，表现为“一部分文字在显示中错误的遗失”，譬如我输入“今天中午的饭是什么？”然后我去编辑下一条文字后，这条文字会奇怪的显示为“今午是？”（当然我只是作比喻），而更换为其他字体似乎暂时能避免此情况出现，但这个问题仍然出现在多种字体上并对我制作场景造成了困难，能否请你尝试寻求造成此问题的原因并提供可能的解决方法？（此场景中大概有十几条总计100多字的中文以及两条由大约数百英文单词组成的小短文，我不知道是导致出现这个问题的原因是否与较多的文本量和文本道具数量有关，亦或是与自动翻译插件有所冲突？游戏环境是最新的KKS HFPatch）

**Comment by Kamisato100** [comment]
而且出现错误显示的文字实际上内容并没有出现遗失，只是显示时遗失了其中一部分文字。我能通过刷新这个文本道具来使其正确显示，但这只会导致使用同样字体的另一个文本道具内容出现同样的显示缺字错误问题。

**Comment by jim60105** [comment]
這是Unity的限制
你可以想成有一個畫布空間，每個文字渲染成圖案後要放在上面才能顯示
具體尺寸我不記得，假設它有100格，當你用到101個字時就會把第1個字擠出去，造成顯示缺失

這個問題對老外來說不是問題，他們只有26個字母，只要26格位子
Unity就是這麼回事，我沒有辦法
