### ISSUE TITLE
FBI does not change the size of the characters chest

### ISSUE THREAD

**Issue by Chase-san** [jim60105/KK#15]
Based on Sunshine BetterRepack R6

On activating the script, the character changes, the animations play, but the chest size is left unaffected.

**Comment by Chase-san** [comment]
Here is an example.
![001](https://user-images.githubusercontent.com/34535/193491617-ba72ba3a-6f8b-4acf-a8a4-ea9cbcddbbb4.jpg)
![002](https://user-images.githubusercontent.com/34535/193491618-683c5f56-e159-4a82-8074-220b2a8ffc91.jpg)
![003](https://user-images.githubusercontent.com/34535/193491619-0a2869e9-09bc-47dc-8f37-28c5adda7377.jpg)

**Comment by jim60105** [comment]
This is a common problem.
The data for the chest is handled by the Pushup plugin, and I didn't inject it.
Please try disabling this plugin and see if the problem is resolved.

Also, this plugin doesn't handle any ABMX data, please make sure her boobs are not using ABMX too much.

**Comment by jim60105** [comment]
If your issue is not related to the above two plugins, please reopen this issue and provide your output logs.
thanks
