### ISSUE TITLE
关于这个 PNG Capture Size Modifier 在Studio读取存档时的一点提议。

### ISSUE THREAD

**Issue by wits-fe** [jim60105/KK#5]
在读取Scene时，弹出的对话框窗口会被放大，能不能加个选项设置让其不放大。
因为放大窗口会拉伸下面的按钮字体，那些字体被模糊放大了。
另一方面，放大的对话框会让已经习惯原大小的人（比如楼主）得更加小心避免点到删除按钮。。
（虽然确实可以在一段时间后适应新窗口大小，如果这个功能不难实现的话还是恳请实现，谢谢）

**Comment by jim60105** [comment]
此插件的主要目的之一就是讓我看清小得不行的scene預覽
如果沒有放大顯示，那麼存成大圖片也沒意義了

另外字體模糊我不打算處理，這是開發成本的事情
現在是直接把LoadScene放大，我只需要一行code便達到目標
如果把按鈕分開會比較麻煩
